// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANZ-kyldi_LvBJcuen3dX2bAO8SE2MlJQ',
    appId: '1:85643944632:web:4262682ae5eb2659234a4d',
    messagingSenderId: '85643944632',
    projectId: 'nerdycatcher',
    authDomain: 'nerdycatcher.firebaseapp.com',
    storageBucket: 'nerdycatcher.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlvs003frhoGOUSeHT8QR5ibeAz9dEVQQ',
    appId: '1:85643944632:android:0ae1298231bd0c94234a4d',
    messagingSenderId: '85643944632',
    projectId: 'nerdycatcher',
    storageBucket: 'nerdycatcher.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqdx7KNSF2M_4T0tN36i9uBs6jXRaz3_Y',
    appId: '1:85643944632:ios:1cc2ee57bd614142234a4d',
    messagingSenderId: '85643944632',
    projectId: 'nerdycatcher',
    storageBucket: 'nerdycatcher.firebasestorage.app',
    iosBundleId: 'com.kangsudal.nerdycatcherFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqdx7KNSF2M_4T0tN36i9uBs6jXRaz3_Y',
    appId: '1:85643944632:ios:1cc2ee57bd614142234a4d',
    messagingSenderId: '85643944632',
    projectId: 'nerdycatcher',
    storageBucket: 'nerdycatcher.firebasestorage.app',
    iosBundleId: 'com.kangsudal.nerdycatcherFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANZ-kyldi_LvBJcuen3dX2bAO8SE2MlJQ',
    appId: '1:85643944632:web:ffc965cf9aaba6a1234a4d',
    messagingSenderId: '85643944632',
    projectId: 'nerdycatcher',
    authDomain: 'nerdycatcher.firebaseapp.com',
    storageBucket: 'nerdycatcher.firebasestorage.app',
  );
}
